# -*- coding: utf-8 -*-
"""Face_recognisiton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gnn0nt1kYaOHg-5YTdMSIwEtoNMyweF9
"""

import numpy as np
import pandas as pd
import cv2 as cv
from matplotlib import pyplot as plt

"""Initializing the webcam which has an id  0"""

cam = cv.VideoCapture(0)

"""loading haarcascade for frontal face classification"""

face_cascade = cv.CascadeClassifier('haarcascade_frontalface_alt.xml')

skip  =0
face_data = []
path ='./data/'
filename = input("Enter ur name")
while True:
  
  retur,frame = cam.read()
  if retur == False:
    continue
  
  faces = face_cascade.detectMultiScale(frame, 1.3,5)
  faces = sorted(faces, key = lambda f:f[2]*f[3], reverse = True)
  
  for face in faces:
    x,y,w,h = face
    cv.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    #crop out required face
    offset = 10
    face_section = frame[y-offset:y+h+1+offset, x-offset:x+w+1+offset]
    face_section = cv.resize(face_section,(100,100))
    #storing every 10th face
    skip+=1
    if skip%10==0:
      face_data.append(face_section)
    cv.imshow("Face section", face_section)
  cv.imshow("Frame",frame)
  
  key_pressed = cv.waitKey(1) & 0xFF
  if key_pressed == ord('q'):
    break

"""convert facelist into numpy array"""

face_data = np.asarray(face_data)
face_data = face_data.reshape((face_data.shape[0],-1))

"""save data in file system"""
np.save(path+filename+".npy", face_data)
print("data successfully save")


cam.release()
cv.destroyAllWindows()
